ATTENTION: This operation should not be executed in a production environment.

CREATE TABLE files_store (id INT AUTO_INCREMENT NOT NULL, store INT DEFAULT NULL, name VARCHAR(255) NOT NULL, size INT NOT NULL, type VARCHAR(120) NOT NULL, INDEX IDX_C565C1BCFF575877 (store), INDEX search_idx (name, type), PRIMARY KEY(id)) ENGINE = InnoDB;
CREATE TABLE files_tagged (file_id INT NOT NULL, tag_id INT NOT NULL, INDEX IDX_3093B19493CB796C (file_id), INDEX IDX_3093B194BAD26311 (tag_id), PRIMARY KEY(file_id, tag_id)) ENGINE = InnoDB;
CREATE TABLE files_tag (id INT AUTO_INCREMENT NOT NULL, tag VARCHAR(100) NOT NULL, UNIQUE INDEX search_idx (tag), PRIMARY KEY(id)) ENGINE = InnoDB;
CREATE TABLE ip_location (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, rango LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', PRIMARY KEY(id)) ENGINE = InnoDB;
CREATE TABLE stores (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(150) NOT NULL, descripcion VARCHAR(255) NOT NULL, capacity BIGINT NOT NULL, UNIQUE INDEX idx_name (name), PRIMARY KEY(id)) ENGINE = InnoDB;
CREATE TABLE files_tag_configuration (id INT AUTO_INCREMENT NOT NULL, store_id INT DEFAULT NULL, tag_id INT DEFAULT NULL, browseable TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_1F397956B092A811 (store_id), UNIQUE INDEX UNIQ_1F397956BAD26311 (tag_id), PRIMARY KEY(id)) ENGINE = InnoDB;
CREATE TABLE files_tags_configuration_ip (tagconfig_id INT NOT NULL, iplocation_ip INT NOT NULL, INDEX IDX_195916673C2A3838 (tagconfig_id), INDEX IDX_19591667D54853DF (iplocation_ip), PRIMARY KEY(tagconfig_id, iplocation_ip)) ENGINE = InnoDB;
ALTER TABLE files_store ADD CONSTRAINT FK_C565C1BCFF575877 FOREIGN KEY (store) REFERENCES stores(id);
ALTER TABLE files_tagged ADD CONSTRAINT FK_3093B19493CB796C FOREIGN KEY (file_id) REFERENCES files_store(id);
ALTER TABLE files_tagged ADD CONSTRAINT FK_3093B194BAD26311 FOREIGN KEY (tag_id) REFERENCES files_tag(id);
ALTER TABLE files_tag_configuration ADD CONSTRAINT FK_1F397956B092A811 FOREIGN KEY (store_id) REFERENCES stores(id);
ALTER TABLE files_tag_configuration ADD CONSTRAINT FK_1F397956BAD26311 FOREIGN KEY (tag_id) REFERENCES files_tag(id);
ALTER TABLE files_tags_configuration_ip ADD CONSTRAINT FK_195916673C2A3838 FOREIGN KEY (tagconfig_id) REFERENCES files_tag_configuration(id);
ALTER TABLE files_tags_configuration_ip ADD CONSTRAINT FK_19591667D54853DF FOREIGN KEY (iplocation_ip) REFERENCES ip_location(id)
